SELECTING_TYPE, SELECTING_REMINDER_ACTION, SELECTING_PLANNER_ACTION = range(3)
ADDING_REMINDER, EDITING_REMINDER, DELETING_REMINDER, SHOWING_REMINDER = range(3, 7)
ADDING_PLANNER, EDITING_PLANNER, DELETING_PLANNER, SHOWING_PLANNER = range(7, 11)
PROMPT_REMINDER_TEXT, PROMPT_REMINDER_DATE, PROMPT_REMINDER_TIME = range(11, 14)
PROMPT_PLANNER_TEXT, PROMPT_PLANNER_DATE = range(14, 16)
REMINDER_TEXT, REMINDER_DATE, REMINDER_TIME = range(16, 19)
PLANNER_TEXT, PLANNER_DATE = range(19, 21)
GO_BACK = 21
